export const _mockReviews = [
  {
    id: 1,
    author: 'João Silva',
    date: '2024-05-05',
    rating: 5,
    description: 'Ótimo produto! Recomendo a todos.',
  },
  {
    id: 2,
    author: 'Maria Souza',
    date: '2024-04-22',
    rating: 4,
    description: 'Produto bom, mas poderia ser melhor.',
  },
  {
    id: 1,
    author: 'João Silva',
    date: '2024-05-05',
    rating: 5,
    description: 'Ótimo produto! Recomendo a todos.',
  },
  {
    id: 2,
    author: 'Maria Souza',
    date: '2024-04-22',
    rating: 4,
    description: 'Produto bom, mas poderia ser melhor.',
  },
  {
    id: 1,
    author: 'João Silva',
    date: '2024-05-05',
    rating: 5,
    description: 'Ótimo produto! Recomendo a todos.',
  },
  {
    id: 2,
    author: 'Maria Souza',
    date: '2024-04-22',
    rating: 4,
    description: 'Produto bom, mas poderia ser melhor.',
  },
  {
    id: 1,
    author: 'João Silva',
    date: '2024-05-05',
    rating: 5,
    description: 'Ótimo produto! Recomendo a todos.',
  },
  {
    id: 2,
    author: 'Maria Souza',
    date: '2024-04-22',
    rating: 4,
    description: 'Produto bom, mas poderia ser melhor.',
  },
  {
    id: 1,
    author: 'João Silva',
    date: '2024-05-05',
    rating: 5,
    description: 'Ótimo produto! Recomendo a todos.',
  },
  {
    id: 2,
    author: 'Maria Souza',
    date: '2024-04-22',
    rating: 4,
    description: 'Produto bom, mas poderia ser melhor.',
  },
  {
    id: 1,
    author: 'João Silva',
    date: '2024-05-05',
    rating: 5,
    description: 'Ótimo produto! Recomendo a todos.',
  },
  {
    id: 2,
    author: 'Maria Souza',
    date: '2024-04-22',
    rating: 4,
    description: 'Produto bom, mas poderia ser melhor.',
  },
];
