version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    db:
        image: postgres:15
        restart: unless-stopped
        environment:
            PGPASSWORD: 'password'
            POSTGRES_DB: 'brecho'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'password'
        volumes:
            - ./.docker/postgresql/dbdata:/var/lib/postgresql
        ports:
            - "5432:5432"
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
