version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./storage:/var/www/html/storage
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./storage:/var/www/html/storage
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    db:
        image: postgres:15
        restart: unless-stopped
        environment:
            PGPASSWORD: 'password'
            POSTGRES_DB: 'brecho'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'password'
        volumes:
            - ./.docker/postgresql/dbdata:/var/lib/postgresql
        ports:
            - "5432:5432"
        networks:
            - laravel

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: unless-stopped
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: rafaelhpmg@gmail.com
            PGADMIN_DEFAULT_PASSWORD: root
        user: '$UID:$GID'
        ports:
            - 8989:80
        volumes:
            - ./.docker/pgadmin/dbdata:/var/lib/pgadmin
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
