version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /app
        ports:
            - "8080:8080"
        volumes:
            - ./:/app
            - ./storage:/app/html/storage
        networks:
            - laravel

#    nginx:
#        image: nginx:alpine
#        restart: unless-stopped
#        ports:
#            - "8080:80"
#        volumes:
#            - ./:/var/www
#            - ./storage:/var/www/html/storage
#            - ./docker/nginx/:/etc/nginx/conf.d/
#        networks:
#            - laravel

networks:
    laravel:
        driver: bridge
